CREATE TABLE "portal_audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" uuid,
	"action" varchar(100) NOT NULL,
	"resource" varchar(100),
	"resourceId" uuid,
	"ipAddress" varchar(45),
	"userAgent" text,
	"details" text,
	"encryptedData" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "portal_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portal_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "portal_role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portal_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "portal_role_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "portal_session" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" uuid NOT NULL,
	"sessionToken" varchar(255) NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"ipAddress" varchar(45),
	"userAgent" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "portal_session_sessionToken_unique" UNIQUE("sessionToken")
);
--> statement-breakpoint
CREATE TABLE "portal_user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(256) NOT NULL,
	"email" varchar(320) NOT NULL,
	"passwordHash" text NOT NULL,
	"roleId" integer DEFAULT 2 NOT NULL,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"lastLoginAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "portal_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "portal_audit_log" ADD CONSTRAINT "portal_audit_log_userId_portal_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."portal_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portal_session" ADD CONSTRAINT "portal_session_userId_portal_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."portal_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portal_user" ADD CONSTRAINT "portal_user_roleId_portal_role_id_fk" FOREIGN KEY ("roleId") REFERENCES "public"."portal_role"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_user_idx" ON "portal_audit_log" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "audit_action_idx" ON "portal_audit_log" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_created_idx" ON "portal_audit_log" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "name_idx" ON "portal_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "role_name_idx" ON "portal_role" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_token_idx" ON "portal_session" USING btree ("sessionToken");--> statement-breakpoint
CREATE INDEX "session_user_idx" ON "portal_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_expires_idx" ON "portal_session" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "portal_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "user_role_idx" ON "portal_user" USING btree ("roleId");